### ISSUE TITLE
list display table broken with date_hierarchy

### ISSUE THREAD

**Issue by MounirMesselmeni** [MaistrenkoAnton/django-material-admin#78]
If using [date_hierarchy](https://docs.djangoproject.com/en/3.0/ref/contrib/admin/#modeladmin-options) in ModelAdmin the table will be displayed on the right and the page will not be usable any more.

![image](https://user-images.githubusercontent.com/1055731/74240926-34773d80-4cdb-11ea-8c73-2a8221a8d973.png)

**Comment by MaistrenkoAnton** [comment]
Fixed in `v1.6.40`

**Comment by MounirMesselmeni** [comment]
@MaistrenkoAnton Thanks for your fast support, unfortunately it still does not work as the style for 
`#changelist-form .results {
    overflow-x: auto;
}`
from Django admin's changelist.css seems to boverwrite your .results maybe we need a `!important` to enforce it

**Comment by MaistrenkoAnton** [comment]
Can't reproduce the issue. From my side it looks:
![Screenshot from 2020-02-12 00-23-14](https://user-images.githubusercontent.com/15648919/74285246-20a8f700-4d2e-11ea-848a-2b2429e78fcc.png)

`overflow-x` shouldn't brake the page. Maybe you have some cached styles? (ctrl+F5)

**Comment by MounirMesselmeni** [comment]
Yeah, I also checked the /static/material/admin/css/changelists.min.css which contains the .results
Using Django 3 btw

![image](https://user-images.githubusercontent.com/1055731/74286922-1d5f3c80-4d29-11ea-8ae2-8154299ea79a.png)

**Comment by MounirMesselmeni** [comment]
Okay, it's because of `width: auto;` also from Django admin
![image](https://user-images.githubusercontent.com/1055731/74287152-93fc3a00-4d29-11ea-89e7-e8a5d3b692ef.png)

**Comment by MounirMesselmeni** [comment]
Ok, the material change list file is loaded after the one from Django admin which is good. But the `.change-list .filter .results` is more [specific](https://www.w3schools.com/css/css_specificity.asp) than `.results`

**Comment by MaistrenkoAnton** [comment]
@MounirMesselmeni, Thank you, your hints were helpful,  I reproduced the issue

Fixed, it should work properly since `v1.6.41`

**Comment by MounirMesselmeni** [comment]
Thanks a lot @MaistrenkoAnton
